/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 swiss_army_knife.glb 
Author: Hadrien59 (https://sketchfab.com/Hadrien59)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/swiss-army-knife-bf9e6f7de2a24d169f3e6236ab3096b4
Title: Swiss Army Knife
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Knife(props) {
  const { nodes, materials } = useGLTF('/models/swiss_army_knife.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.blinn2SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert2SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.blinn1SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.blinn1SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/swiss_army_knife.glb')
