/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 swiss_army_knife.glb 
Author: Hadrien59 (https://sketchfab.com/Hadrien59)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/swiss-army-knife-bf9e6f7de2a24d169f3e6236ab3096b4
Title: Swiss Army Knife
*/

import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from 'three'

export function Knife(props) {
     const matcapTexture = useTexture('/images/textures/mat1.png')
  const { nodes, materials } = useGLTF('/models/swiss_army_knife.glb')

  const curtainMaterial = new THREE.MeshPhongMaterial({ color: "#D90429" })
  
  const bodyMaterial = new THREE.MeshPhongMaterial({
    map: matcapTexture
  })

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={curtainMaterial} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert2SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.blinn1SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.blinn1SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/swiss_army_knife.glb')
